# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default=b'WELCOME TO LOGICON HEADQUARTERS OUR TEAM COMBINES STRONG TECHNICAL KNOW HOW WITH THE ABILITY TO DELIVER HIGHLY POLISHED SOLUTIONS.', help_text=b'Heading under the logo', max_length=200),
        ),
    ]
