# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20161012_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='highlighted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default=b'WELCOME TO LOGICON HEADQUARTERS OUR TEAM COMBINES STRONG TECHNICAL KNOW HOW WITH THE ABILITY TO DELIVER HIGHLY POLISHED SOLUTIONS.', help_text=b'Heading under the logo', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='portfolio_heading',
            field=models.CharField(default=b'Portfolio', help_text=b'The portfolio heading', max_length=200),
        ),
    ]
