# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:32
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20161012_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo_icon',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
    ]
