# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_homepage_logo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=models.CharField(default=(b'One of our team would be happy to discuss in detail our skillset and experience', b' and how we fit in with your project. Send us an email using the link below.'), help_text=b'Text for contact section', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(default=b'WELCOME TO LOGICON HEADQUARTERS. OUR TEAM COMBINES STRONG TECHNICAL KNOW HOW WITH THE ABILITY TO DELIVER HIGHLY POLISHED SOLUTIONS.', help_text=b'Heading under the logo', max_length=500),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo_icon',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_heading',
            field=models.CharField(default=b'Services', help_text=b'The services heading', max_length=200),
        ),
    ]
