# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 07:21
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20161012_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=mezzanine.core.fields.RichTextField(default=b'WELCOME TO LOGICON HEADQUARTERS. OUR TEAM COMBINES STRONG TECHNICAL KNOW HOW WITH THE ABILITY TO DELIVER HIGHLY POLISHED SOLUTIONS.', help_text=b'Heading under the logo', max_length=500),
        ),
    ]
