# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_homepage_map_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplace',
            name='msg',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
