# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_mapplace_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapplace',
            name='msg',
            field=models.CharField(help_text=b'Msg when user clicks marker. Use %LOC_PLACEHOLDER% as placeholder for location in your text.', max_length=200),
        ),
    ]
