# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 22:23
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_auto_20161014_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='bg_global_img',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Global background'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_img',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Footer background'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='modal_img',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Portfolio modal background'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_img',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Portfolio background'),
        ),
    ]
